--- Luawk default runtime.
--
-- You can test the environment from command-line using the following command:
--     lua -e 'R=require("luawk.runtime").new()' -i
--     Lua 5.4.4  Copyright (C) 1994-2022 Lua.org, PUC-Rio
--     > R.OFS=","
--     > R[0]="a b c"
--     > R.NF
--     3
--     > R[R.NF+1]="d"
--     > R.NF
--     4
--     > for i,v in ipairs(R) do print(i,v) end
--     1,a
--     2,b
--     3,c
--     4,d
--
-- @usage require("luawk.runtime").new()
-- @alias M
-- @module runtime
-- @see posix
-- @see gnu

return require "luawk.environment.gnu"